[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
typeshare = { workspace = true }
serde = { workspace = true }
uuid = { version = "1", features = ["serde"] }
chrono = { version = "0.4.38", features = ["serde"] }