/*
 Generated by typeshare 1.0.0
*/

export interface User {
	id: string;
	first_name: string;
	last_name: string;
	created_at: Date;
	updated_at: Date;
}

export interface Session {
	id: string;
	user_id: string;
	expires_at: Date;
	created_at: Date;
	updated_at: Date;
}

export interface UserCredentials {
	user_id: string;
	email: string;
	hashed_password: string;
	created_at: Date;
	updated_at: Date;
}

export interface SignUpInput {
	email: string;
	password: string;
	first_name: string;
	last_name: string;
}

export interface LoginWithEmailInput {
	email: string;
	password: string;
}

